# Generated by Django 4.2.5 on 2023-09-28 09:48

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PetType',
            fields=[
                ('pettype_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='PetBreed',
            fields=[
                ('petbreed_id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('pettype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pettype')),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(db_column='pet_id', primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Age must be at least 1.'), django.core.validators.MaxValueValidator(30, message='Age must be at most 30.')])),
                ('height', models.CharField(max_length=10)),
                ('weight', models.CharField(max_length=10)),
                ('color', models.CharField(max_length=15)),
                ('is_vacinated', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pettype')),
            ],
        ),
    ]
