# Generated by Django 4.2.5 on 2023-10-01 07:45

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetPrice',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Price', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='Price must be greater than 0')])),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PKR', 'PKR'), ('IND', 'INR'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('Pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pet')),
            ],
        ),
        migrations.CreateModel(
            name='Feed',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=250)),
                ('Description', models.CharField(max_length=500)),
                ('price', models.IntegerField(verbose_name=django.core.validators.MinValueValidator(1, message='Price must be greater than 0'))),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('PKR', 'PKR'), ('IND', 'INR'), ('EUR', 'Euro'), ('GBP', 'British Pound')], max_length=3)),
                ('pet_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pets.pettype')),
            ],
        ),
    ]
